I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 21, in script call
    "My Room | May 29th, 2018"
  File "renpy/common/00console.rpy", line 765, in script call
    python in _console:
  File "game/script.rpy", line 488, in script
    with fadein
  File "game/script.rpy", line 488, in <module>
    with fadein
NameError: name 'fadein' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 21, in script call
    "My Room | May 29th, 2018"
  File "renpy/common/00console.rpy", line 765, in script call
    python in _console:
  File "game/script.rpy", line 488, in script
    with fadein
  File "C:\renpy\renpy-6.99.14.3-sdk\renpy\ast.py", line 1350, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\renpy\renpy-6.99.14.3-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\renpy\renpy-6.99.14.3-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 488, in <module>
    with fadein
NameError: name 'fadein' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.1.929
The Good Christian Visual Novel 1.0
Sat May 25 12:56:00 2019
